services:
  crab-bot:
    build: .
    container_name: crab-bot
    image: crab-bot:latest
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      # - ./recipes.json:/app/recipes.json 
      - /home/deploy_gha_user/crab-data/recipes.json:/app/recipes.json